### ISSUE TITLE
템플릿 내 스타일 태그 사용 시 해당 템플릿을 사용할 때마다 중복적으로 스타일 태그가 적용됨

### ISSUE THREAD

**Issue by hseoy** [woowa-techcamp-2021/baemin-9#15]
현재 컴포넌트 폴더 내의 템플릿 파일들은 내부에 스타일 태그를 지니고 있습니다.
그러나 이러한 스타일 태그들이 템플릿을 여러 번 포함시킬 때마다 중복적으로 head에 추가되고 있습니다.

**Comment by LeagueLugas** [comment]
각 컴포넌트마다 각각의 css파일을 가져오는 방식을 알아보묜 좋을거 같아요

**Comment by hseoy** [comment]
각 컴포넌트에 대해서 내부에 스타일 태그를 사용하지 말고 하나의 css 파일을 만들고 해당 컴포넌트를 사용하는 페이지에서 해당 파일을 한번만 포함시키는 방식으로 해결하면 될 것 같습니다.
